# galay-mail build options

if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
    set(CMAKE_INSTALL_PREFIX /usr/local CACHE PATH "Install path prefix" FORCE)
endif()

option(BUILD_TESTS "Legacy alias for BUILD_TESTING" OFF)
option(BUILD_EXAMPLES "Build example executables" ON)
option(BUILD_SHARED_LIBS "Build shared library instead of static" ON)
option(GALAY_MAIL_INSTALL_MODULE_INTERFACE "Install C++ module interface files (*.cppm)" ON)
option(GALAY_MAIL_ENABLE_IMPORT_COMPILATION "Enable C++ import/module compilation path" OFF)

option(DISABLE_IOURING "Disable io_uring and use epoll on Linux" ON)

function(configure_io_backend)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        if(DISABLE_IOURING)
            add_compile_definitions(USE_EPOLL)
            set(GALAY_MAIL_BACKEND "epoll" PARENT_SCOPE)
        else()
            find_library(URING_LIB uring)
            if(URING_LIB)
                add_compile_definitions(USE_IOURING)
                set(GALAY_MAIL_BACKEND "io_uring" PARENT_SCOPE)
                set(PLATFORM_LIBS ${URING_LIB} PARENT_SCOPE)
            else()
                add_compile_definitions(USE_EPOLL)
                set(GALAY_MAIL_BACKEND "epoll" PARENT_SCOPE)
            endif()
        endif()
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        add_compile_definitions(USE_KQUEUE)
        set(GALAY_MAIL_BACKEND "kqueue" PARENT_SCOPE)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
        add_compile_definitions(USE_IOCP)
        set(GALAY_MAIL_BACKEND "iocp" PARENT_SCOPE)
    else()
        set(GALAY_MAIL_BACKEND "unknown" PARENT_SCOPE)
    endif()
endfunction()
